# Generated by Django 5.2.7 on 2025-10-03 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_notesummary_unit_number_alter_notesummary_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesummary',
            old_name='uploaded_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='notesummary',
            old_name='summary_text',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='notesummary',
            name='subject_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notesummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
